### PR TITLE
Localhost

### PR DESCRIPTION
**Pull request by mreeve**

### CODE REVIEW

**Comment by mreeve** [comment]
Didn't mean to submit

**Comment by ghost** [comment]
Do your changes work? or are you testing?

**Comment by mreeve** [comment]
It doesn't work yet. I'm hoping to get it updated to php8.2 and other changes: traefik, possibly other monitoring down the road. I ran into testing things locally, my ISP seems to be blocking every inbound port. Argh!

**Comment by ghost** [comment]
Hey @mreeve 
I spent a day or so on the code, and I've got it working.
Check it out here: https://github.com/voryzen/hubzilla

I've put the code on my fork, and uploaded a built copy to docker hub (voryzen/hubzilla)

Hope this helps you out

**Pull request closed without merging**
